
---
include:
  - board: nice_nano_v2
    shield: sofle_dongle dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_receptor_international
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DUSE_INTERNATIONAL_LAYOUT
  - board: nice_nano_v2
    shield: sofle_dongle dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_receptor_abnt2
  - board: nice_nano_v2
    shield: sofle_left
    artifact-name: sofle_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: sofle_right
    artifact-name: sofle_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: reset-firmware
  - board: nice_nano_v2
    shield: sofle_dongle_home dongle_display_home
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_receptor_international_home
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DUSE_INTERNATIONAL_LAYOUT
  - board: nice_nano_v2
    shield: sofle_dongle_home dongle_display_home
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_receptor_abnt2_home
  - board: nice_nano_v2
    shield: sofle_dongle_work dongle_display_work
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_receptor_international_work
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DUSE_INTERNATIONAL_LAYOUT
  - board: nice_nano_v2
    shield: sofle_dongle_work dongle_display_work
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_receptor_abnt2_work